version: '3.0'

tasks:
  build:
    desc: "Build Executable"
    cmds:
      - npx pkg bin/main-bundle.js --output ppipe.exe --targets node14-win-x64
  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - ./test.sh

  clean:
    desc: "Clean up"
    cmds:
      - echo "Cleaning up..."
      - rm -f myapp

  all:
    desc: "Build, test, and clean the project"
    deps: [build, test, clean]
