CREATE TABLE IF NOT EXISTS ProxyObj (
    id SERIAL PRIMARY KEY,
    ip VARCHAR(255) NOT NULL,
    ms INT NOT NULL,
    meta JSONB,
    groupId VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

